## Coding Practice

## NumPy



## Create 1D and 2D arrays.

In [2]:
import numpy as np

In [3]:
list1 = [1, 2, 3, 4, 5]
list2 = [[6, 7], [8, 9]]

arr1 = np.array(list1)
arr2 = np.array(list2)

print(arr1)
print(arr2)


[1 2 3 4 5]
[[6 7]
 [8 9]]


## Perform arithmetic operations on arrays.

In [13]:
arr = arr1 + 10
print(arr)

arr = arr2 * 2
print(arr)

arr = arr1 - 2
print(arr)

arr = arr2/2
print(arr)

[11 12 13 14 15]
[[12 14]
 [16 18]]
[-1  0  1  2  3]
[[3.  3.5]
 [4.  4.5]]


## Find the maximum, minimum, mean, and sum of an array.

In [18]:
arr = np.arange(1,100,3)
mx = arr.max()
mn = arr.min()
arr_mean = arr.mean()
arr_sum = arr.sum()

print(f'maximum : {mx} \nminimum: {mn} \nmean: {arr_mean}\nsum: {arr_sum} \n')


maximum : 97 
minimum: 1 
mean: 49.0
sum: 1617 



## Reshape arrays into different dimensions.

In [32]:
arr = np.linspace(0,5,10)
arr1 = arr.reshape(2,5)

arr2 = np.random.randint(5, size=(2,3))
arr3 = arr2.reshape(3,2)

print(arr)
print(arr1)
print(arr2)
print(arr3)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[[0.         0.55555556 1.11111111 1.66666667 2.22222222]
 [2.77777778 3.33333333 3.88888889 4.44444444 5.        ]]
[[0 2 3]
 [4 4 1]]
[[0 2]
 [3 4]
 [4 1]]


## Slice and index arrays.

In [33]:
arr1 = np.linspace(0,5,10)
print(arr1)
print(arr1[0])
print(arr1[-1])
print(arr1[::-1])
print(arr1[arr1>3])
print(arr1[::3])

arr2 = np.random.randint(5, size=(2,3))
print(arr2)
print(arr2[0])
print(arr2[-1])
print(arr2[0][0])
print(arr2[-1][-1])
print(arr2[::-1])
print(arr2[arr2>3])
print(arr2[::3])


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
0.0
5.0
[5.         4.44444444 3.88888889 3.33333333 2.77777778 2.22222222
 1.66666667 1.11111111 0.55555556 0.        ]
[3.33333333 3.88888889 4.44444444 5.        ]
[0.         1.66666667 3.33333333 5.        ]
[[4 3 3]
 [4 2 4]]
[4 3 3]
[4 2 4]
4
4
[[4 2 4]
 [4 3 3]]
[4 4 4]
[[4 3 3]]
